# 🔢 NumPy — Session 1: Complete Foundations

> **Topics Covered:**
> 1. Why NumPy?
> 2. Creating NumPy Arrays
> 3. Array Attributes & Properties
> 4. NumPy Data Types
> 5. Indexing & Slicing
> 6. Memory Concepts
> 7. Type Casting (Upcasting & Downcasting)
> 8. Logical Operations
> 9. Handling NaN and Infinite Values
> 10. Assignments

---

In [128]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 📦 Import NumPy

The convention is to import NumPy with the alias `np`. This is universally followed across the data ecosystem.

In [129]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.24.4


---

## 1️⃣ Why NumPy?

Python lists are flexible but **slow** for numerical computation. NumPy solves this.

### Key Advantages:
| Feature | Python List | NumPy Array |
|---|---|---|
| Speed | Slow (interpreted loop) | Fast (C under the hood) |
| Memory | High (stores objects) | Low (stores raw bytes) |
| Operations | Manual loops needed | Vectorized (no loops) |
| Data type | Mixed types allowed | Homogeneous (same type) |
| Math support | Limited | Full scientific support |

### Why does speed matter?
When you're processing **millions of sensor readings, stock prices, or ML features** — microseconds add up to minutes.

In [130]:
import time

size = 1_000_000

# Python list approach
py_list = list(range(size))
start = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start

# NumPy approach
np_arr = np.arange(size)
start = time.time()
np_result = np_arr * 2
np_time = time.time() - start

print(f"Python list time : {py_time:.4f} seconds")
print(f"NumPy array time : {np_time:.4f} seconds")
print(f"NumPy is ~{py_time / np_time:.1f}x faster!")

Python list time : 0.2102 seconds
NumPy array time : 0.0089 seconds
NumPy is ~23.6x faster!


In [131]:
type(np_arr)

numpy.ndarray

In [132]:
# Memory comparison
import sys

py_list_small = list(range(1000))
np_arr_small  = np.arange(1000, dtype=np.int64)

py_mem = sys.getsizeof(py_list_small)  # bytes for the list object
np_mem = np_arr_small.nbytes           # bytes for the raw data

print(f"Python list memory : {py_mem} bytes")
print(f"NumPy array memory : {np_mem} bytes")

Python list memory : 8056 bytes
NumPy array memory : 8000 bytes


### NumPy integrates with the whole ecosystem:
- **Pandas** — DataFrames are built on NumPy arrays internally
- **Matplotlib** — Plots data from NumPy arrays
- **Scikit-Learn** — Expects NumPy arrays as input
- **TensorFlow / PyTorch** — Tensors are inspired by NumPy's ndarray

---

## 2️⃣ Creating NumPy Arrays

The core data structure in NumPy is the **`ndarray`** (N-Dimensional Array).

### What is ndarray?
- A grid of values, **all of the same type**
- Indexed by a tuple of non-negative integers
- Stored in a **contiguous block of memory** (unlike Python lists)

In [4]:
# ── 1D Array ──────────────────────────────────────────────
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)
print("Type     :", type(arr_1d))
print("ndim     :", arr_1d.ndim)   # number of dimensions

1D Array: [10 20 30 40 50]
Type     : <class 'numpy.ndarray'>
ndim     : 1


In [6]:
# ── 2D Array (Matrix) ─────────────────────────────────────
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array:\n", arr_2d)
print("ndim:", arr_2d.ndim)

2D Array:
 [[1 2 3]
 [4 5 6]]
ndim: 2


In [7]:
# ── 3D Array ──────────────────────────────────────────────
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)
print("ndim:", arr_3d.ndim)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [137]:
print([i for i in range(0,10,2)])

for i in range(0,10,2):
    print(i)

[0, 2, 4, 6, 8]
0
2
4
6
8


In [ ]:
# ── Array creation helpers ─────────────────────────────────

# zeros: all elements = 0
print("zeros (2x3):\n", np.zeros((2, 3)))

# ones: all elements = 1
print("ones (2x4):\n", np.ones((2, 4)))

# arange: like Python range(), returns array
print("arange(0,10,2):", np.arange(0, 10, 2))
print("arange(0,10,3):", np.arange(0, 10, 3))

# linspace: evenly spaced values between start and stop
# np.linespace('start','end','num')
# (stop-start)/(num -1) 
print("linspace(0,1,5):", np.linspace(0, 1, 5))
print("linspace(10,20,6):", np.linspace(10, 20, 6))
# 10/5 = 2
# 10 
# 10+2 =12
# 12+2 = 14
# 14+2 = 16
# 16+2 = 18
# 18+2  = 20 

# full: fill with a constant value
print("full (2x2, val=7):\n", np.full((2, 2), 7))
print("full (2x3, val=8):\n", np.full((2, 3), 7))

# eye: identity matrix
print("eye (3x3):\n", np.eye(3))
print("eye (4x4):\n", np.eye(4))

zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
ones (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arange(0,10,2): [0 2 4 6 8]
arange(0,10,3): [0 3 6 9]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
linspace(10,20,6): [10. 12. 14. 16. 18. 20.]
full (2x2, val=7):
 [[7 7]
 [7 7]]
full (2x3, val=8):
 [[7 7 7]
 [7 7 7]]
eye (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eye (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 🔑 Key concept: Homogeneous Data
NumPy arrays can only hold **one data type**. If you mix types, NumPy will **upcast** to accommodate all values.

In [14]:
mixed = np.array([1, 2.5, 3])     # int + float → all become float
print("Mixed int+float dtype:", mixed.dtype, "| values:", mixed)

mixed2 = np.array([1, 2, 'three'])  # int + string → all become string
print("Mixed int+str   dtype:", mixed2.dtype, "| values:", mixed2)

val = np.array(['A'])
print("Type of val: ", val.dtype)

Mixed int+float dtype: float64 | values: [1.  2.5 3. ]
Mixed int+str   dtype: <U11 | values: ['1' '2' 'three']
Type of val:  <U1


---

## 3️⃣ Array Attributes & Properties

Once you have an array, these attributes tell you everything about it.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:\n", arr)
print()
print("shape    :", arr.shape)      # (rows, cols) → (2, 3)
print("ndim     :", arr.ndim)       # number of dimensions → 2
print("dtype    :", arr.dtype)      # data type → int64
print("size     :", arr.size)       # total elements → 6
print("itemsize :", arr.itemsize,   # bytes per element → 8 (int64 = 8 bytes)
      "bytes per element")
print("nbytes   :", arr.nbytes,     # total memory = size × itemsize
      "bytes total")

Array:
 [[1 2 3]
 [4 5 6]]

shape    : (2, 3)
ndim     : 2
dtype    : int32
size     : 6
itemsize : 4 bytes per element
nbytes   : 24 bytes total


In [ ]:
# Self Understanding block

arr = np.array([[1, 2, 3],
                [4, 5, 6]],dtype=np.int64)

print("Array:\n", arr)
print()
print("shape    :", arr.shape)      # (rows, cols) → (2, 3)
print("ndim     :", arr.ndim)       # number of dimensions → 2
print("dtype    :", arr.dtype)      # data type → int64
print("size     :", arr.size)       # total elements → 6
print("itemsize :", arr.itemsize,   # bytes per element → 8 (int64 = 8 bytes)
      "bytes per element")
print("nbytes   :", arr.nbytes,     # total memory = size × itemsize
      "bytes total")

Array:
 [[1 2 3]
 [4 5 6]]

shape    : (2, 3)
ndim     : 2
dtype    : int64
size     : 6
itemsize : 8 bytes per element
nbytes   : 48 bytes total


In [ ]:
# Understanding shape deeply

a = np.array([1, 2, 3])              # shape: (3,)    → 1D, 3 elements
b = np.array([[1, 2, 3]])            # shape: (1, 3)  → 2D, 1 row 3 cols
c = np.array([[1], [2], [3]])        # shape: (3, 1)  → 2D, 3 rows 1 col
d = np.zeros((2, 3, 4))             # shape: (2, 3, 4) → 3D      --> (shape) = (layers, rows, columns)

for name, arr in [('a', a), ('b', b), ('c', c), ('d', d)]:
    print(f"{name}: shape={arr.shape}, ndim={arr.ndim}, size={arr.size}")

a: shape=(3,), ndim=1, size=3
b: shape=(1, 3), ndim=2, size=3
c: shape=(3, 1), ndim=2, size=3
d: shape=(2, 3, 4), ndim=3, size=24


In [24]:
print(d)
print("-"*40)
print(d[0])

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
----------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


---

## 4️⃣ NumPy Data Types (`dtype`)

Choosing the right dtype is critical for **memory optimization** — especially important in Data Engineering when handling large datasets.

### Integer Types
| dtype | Bits | Range |
|---|---|---|
| int8 | 8 | -128 to 127 |
| int16 | 16 | -32,768 to 32,767 |
| int32 | 32 | -2.1B to 2.1B |
| int64 | 64 | -9.2e18 to 9.2e18 |
| uint8 | 8 | 0 to 255 |
| uint16 | 16 | 0 to 65,535 |

In [138]:
# Integer types
i8  = np.array([100], dtype=np.int8)
i16 = np.array([100], dtype=np.int16)
i32 = np.array([100], dtype=np.int32)
i64 = np.array([100], dtype=np.int64)

for name, arr in [('int8', i8), ('int16', i16), ('int32', i32), ('int64', i64)]:
    print(f"{name:6s} | itemsize={arr.itemsize} bytes | value={arr[0]}")

int8   | itemsize=1 bytes | value=100
int16  | itemsize=2 bytes | value=100
int32  | itemsize=4 bytes | value=100
int64  | itemsize=8 bytes | value=100


In [26]:
# What happens when you exceed the range? → Overflow!
overflow = np.array([200], dtype=np.int8)   # int8 max is 127
print("200 stored as int8:", overflow[0])   # wraps around!

200 stored as int8: -56


C:\Users\tadit\AppData\Local\Temp\ipykernel_22172\4214037496.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([200], dtype=np.int8)   # int8 max is 127


In [27]:
# Unsigned integers (no negative values, double positive range)
u8  = np.array([200], dtype=np.uint8)   # 0 to 255 ✅
print("200 as uint8:", u8[0])

# Float types
f16 = np.array([3.14], dtype=np.float16)
f32 = np.array([3.14], dtype=np.float32)
f64 = np.array([3.14], dtype=np.float64)

print()
for name, arr in [('float16', f16), ('float32', f32), ('float64', f64)]:
    print(f"{name:8s} | itemsize={arr.itemsize} bytes | value={arr[0]}")

200 as uint8: 200

float16  | itemsize=2 bytes | value=3.140625
float32  | itemsize=4 bytes | value=3.140000104904175
float64  | itemsize=8 bytes | value=3.14


In [28]:
# Complex types (real + imaginary parts)
c64  = np.array([1+2j], dtype=np.complex64)
c128 = np.array([1+2j], dtype=np.complex128)
print("complex64 :", c64[0],  "| itemsize:", c64.itemsize)
print("complex128:", c128[0], "| itemsize:", c128.itemsize)

# Boolean
b = np.array([True, False, True], dtype=np.bool_)
print("bool array:", b, "| dtype:", b.dtype)

# String
s = np.array(['Alice', 'Bob', 'Charlie'], dtype=np.str_)
print("str array :", s, "| dtype:", s.dtype)

complex64 : (1+2j) | itemsize: 8
complex128: (1+2j) | itemsize: 16
bool array: [ True False  True] | dtype: bool
str array : ['Alice' 'Bob' 'Charlie'] | dtype: <U7


In [ ]:
# Real-world scenario: memory saving with smart dtype choice
n = 1_000_000  # is same as 1000000 because python allow '_' in numeric value for better readability

arr_int64 = np.ones(n, dtype=np.int64)
arr_int8  = np.ones(n, dtype=np.int8)

print(f"int64 array: {arr_int64.nbytes / 1024 / 1024:.2f} MB")  # bytes -> kb -> MB
print(f"int8  array: {arr_int8.nbytes  / 1024 / 1024:.2f} MB")
print(f"Saved: {(arr_int64.nbytes - arr_int8.nbytes) / 1024 / 1024:.2f} MB")

int64 array: 7.63 MB
int8  array: 0.95 MB
Saved: 6.68 MB


---

## 5️⃣ Indexing & Slicing

### 1D Indexing

In [139]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Positive indexing (left to right, starts at 0)
print("arr[0]  :", arr[0])    # first element
print("arr[3]  :", arr[3])    # 4th element

# Negative indexing (right to left, starts at -1)
print("arr[-1] :", arr[-1])   # last element
print("arr[-2] :", arr[-2])   # second-last

print(arr[4:])

arr[0]  : 10
arr[3]  : 40
arr[-1] : 70
arr[-2] : 60
[50 60 70]


In [31]:
# Slicing: arr[start : stop : step]
# stop is EXCLUSIVE (element at stop index is NOT included)

print("arr[1:4]   :", arr[1:4])    # index 1,2,3
print("arr[:3]    :", arr[:3])     # from start to index 2
print("arr[4:]    :", arr[4:])     # from index 4 to end
print("arr[::2]   :", arr[::2])    # every 2nd element
print("arr[::-1]  :", arr[::-1])   # reverse the array

arr[1:4]   : [20 30 40]
arr[:3]    : [10 20 30]
arr[4:]    : [50 60 70]
arr[::2]   : [10 30 50 70]
arr[::-1]  : [70 60 50 40 30 20 10]


In [ ]:
# 2D Indexing: arr[row, col]
arr_2d = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])

print("Type of Dimension:",arr_2d.ndim)

print("Array:\n", arr_2d)
print()

# Single element
print("arr_2d[0, 0] :", arr_2d[0, 0])   # row 0, col 0 → 1
print("arr_2d[1, 2] :", arr_2d[1, 2])   # row 1, col 2 → 7
print("arr_2d[2, -1]:", arr_2d[2, -1])  # row 2, last col → 12

Type of Dimension 2
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr_2d[0, 0] : 1
arr_2d[1, 2] : 7
arr_2d[2, -1]: 12


In [36]:
# Row and column selection
print("Row 0       :", arr_2d[0, :])       # entire first row
print("Col 1       :", arr_2d[:, 1])       # entire second column
print("Last row    :", arr_2d[-1, :])      # last row

Row 0       : [1 2 3 4]
Col 1       : [ 2  6 10]
Last row    : [ 9 10 11 12]


In [37]:
# Sub-array slicing: arr[row_start:row_stop, col_start:col_stop]
print("Rows 0-1, Cols 1-2:\n", arr_2d[0:2, 1:3])
print()
print("All rows, Cols 0-1:\n", arr_2d[:, 0:2])
print()
print("Rows 1-2, All cols:\n", arr_2d[1:, :])

Rows 0-1, Cols 1-2:
 [[2 3]
 [6 7]]

All rows, Cols 0-1:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]

Rows 1-2, All cols:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
# Fancy indexing: select specific rows/cols using a list of indices
arr = np.array([100, 200, 300, 400, 500])
print("arr[[0, 2, 4]]:", arr[[0, 2, 4]])   # select index 0, 2, 4

# Fancy indexing on 2D
print("arr_2d[[0,2], :]:\n", arr_2d[[0, 2], :])  # rows 0 and 2

arr[[0, 2, 4]]: [100 300 500]
arr_2d[[0,2], :]:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


### ⚠️ Slices are VIEWS, not copies!
Modifying a slice modifies the original array.

In [42]:
original = np.array([1, 2, 3, 4, 5])
view     = original[1:4]   # this is a VIEW
print("value of view:",view)
view[0] = 999              # modifying view
print("original after modifying view:", original)  # original also changes!

# To avoid this, use .copy()
original2 = np.array([1, 2, 3, 4, 5])
copy_arr  = original2[1:4].copy()
print("value of copy_arr", copy_arr)
copy_arr[0] = 999
print("original2 after modifying copy:", original2)  # unchanged ✅
print("value of copy_arr after modifying: ", copy_arr)

value of view: [2 3 4]
original after modifying view: [  1 999   3   4   5]
value of copy_arr [2 3 4]
original2 after modifying copy: [1 2 3 4 5]
value of copy_arr after modifying:  [999   3   4]


---

## 6️⃣ Memory Concepts

Understanding memory is essential in Data Engineering — especially with large-scale data pipelines.

In [43]:
# itemsize = bytes per element
# nbytes   = total bytes = size × itemsize

dtypes = [np.int8, np.int16, np.int32, np.int64,
          np.float16, np.float32, np.float64]

print(f"{'dtype':<12} {'itemsize':>8} {'nbytes for 1M elements':>25}")
print("-" * 48)
for dt in dtypes:
    arr = np.ones(1_000_000, dtype=dt)
    print(f"{str(dt.__name__):<12} {arr.itemsize:>8} bytes {arr.nbytes/1024/1024:>20.2f} MB")

dtype        itemsize    nbytes for 1M elements
------------------------------------------------
int8                1 bytes                 0.95 MB
int16               2 bytes                 1.91 MB
int32               4 bytes                 3.81 MB
int64               8 bytes                 7.63 MB
float16             2 bytes                 1.91 MB
float32             4 bytes                 3.81 MB
float64             8 bytes                 7.63 MB


In [ ]:
# Contiguous memory layout
# NumPy stores arrays in contiguous memory → cache-friendly → FAST

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.dtype)
print("C-contiguous (row-major)  :", arr.flags['C_CONTIGUOUS'])
print("F-contiguous (col-major)  :", arr.flags['F_CONTIGUOUS'])
print("Strides (bytes between elements):", arr.strides)
# strides: (12, 4) means → move 12 bytes to next row, 4 bytes to next col (int32)

# 1000 1004 1008 1012
#  +----+----+----+----+
#  | 1  | 2  | 3  | 4  |
#  +----+----+----+----+

int32
C-contiguous (row-major)  : True
F-contiguous (col-major)  : False
Strides (bytes between elements): (12, 4)


---

## 7️⃣ Type Casting

### Upcasting
When two arrays of different types are combined, NumPy automatically promotes to the **larger/more precise** type.

In [45]:
# Upcasting examples

int_arr   = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.5, 2.5, 3.5], dtype=np.float64)

result = int_arr + float_arr   # int32 + float64 → float64
print("int32 + float64 result dtype :", result.dtype)
print("Result                        :", result)

# bool + int → int
bool_arr = np.array([True, False, True])
int_arr2 = np.array([10, 20, 30])
r2 = bool_arr + int_arr2
print("\nbool + int result dtype:", r2.dtype, "| values:", r2)

int32 + float64 result dtype : float64
Result                        : [2.5 4.5 6.5]

bool + int result dtype: int32 | values: [11 20 31]


### Downcasting with `.astype()`
Used to reduce memory usage. But beware of **precision loss**.

In [46]:
# float64 → int32 (loses decimal part)
f = np.array([1.9, 2.7, 3.1, 4.99])
i = f.astype(np.int32)
print("float64 original :", f)
print("int32 downcast   :", i)   # decimals are TRUNCATED, not rounded

float64 original : [1.9  2.7  3.1  4.99]
int32 downcast   : [1 2 3 4]


In [47]:
# int64 → int8 (overflow risk!)
big = np.array([1000, 200, 50], dtype=np.int64)
small = big.astype(np.int8)
print("int64 values :", big)
print("int8 downcast:", small)   # 1000 overflows!

int64 values : [1000  200   50]
int8 downcast: [-24 -56  50]


In [ ]:
# float64 → float32 (less precision but half the memory)
precise = np.array([3.141592653589793], dtype=np.float64)
less    = precise.astype(np.float32)
print("float64:", precise[0])
print("float32:", less[0])

# # Safe downcast check
# arr = np.array([1, 2, 3, 255])
# can_fit = (arr.max() <= np.iinfo(np.uint8).max) and (arr.min() >= 0)
# print("\nCan safely cast to uint8?:", can_fit)

float64: 3.141592653589793
float32: 3.1415927

Can safely cast to uint8?: True


---

## 8️⃣ Logical Operations

Logical operations return **boolean arrays** — very useful for filtering and masking.

In [49]:
a = np.array([True,  True,  False, False])
b = np.array([True,  False, True,  False])

print("a              :", a)
print("b              :", b)
print()
print("logical_and    :", np.logical_and(a, b))   # True only if BOTH are True
print("logical_or     :", np.logical_or(a, b))    # True if AT LEAST ONE is True
print("logical_not(a) :", np.logical_not(a))      # flip True/False
print("logical_xor    :", np.logical_xor(a, b))   # True if exactly ONE is True

a              : [ True  True False False]
b              : [ True False  True False]

logical_and    : [ True False False False]
logical_or     : [ True  True  True False]
logical_not(a) : [False False  True  True]
logical_xor    : [False  True  True False]


In [50]:
# Real-world use case: Boolean masking for filtering
sales = np.array([1500, 800, 2200, 450, 3100, 900, 1750])

# Find sales above 1000
mask = sales > 1000
print("Sales array  :", sales)
print("Mask (>1000) :", mask)
print("Filtered     :", sales[mask])

Sales array  : [1500  800 2200  450 3100  900 1750]
Mask (>1000) : [ True False  True False  True False  True]
Filtered     : [1500 2200 3100 1750]


In [51]:
# Combining conditions with logical operations
# Sales between 1000 and 2500
mask_combined = np.logical_and(sales > 1000, sales < 2500)
print("Sales between 1000-2500:", sales[mask_combined])

# Sales < 500 OR > 3000
mask_extreme = np.logical_or(sales < 500, sales > 3000)
print("Sales below 500 or above 3000:", sales[mask_extreme])

Sales between 1000-2500: [1500 2200 1750]
Sales below 500 or above 3000: [ 450 3100]


In [52]:
# Comparison operators create boolean arrays directly
arr = np.array([3, 7, 1, 9, 4, 6, 2])

print("arr > 5       :", arr > 5)
print("arr == 4      :", arr == 4)
print("arr != 1      :", arr != 1)
print("arr >= 6      :", arr >= 6)

arr > 5       : [False  True False  True False  True False]
arr == 4      : [False False False False  True False False]
arr != 1      : [ True  True False  True  True  True  True]
arr >= 6      : [False  True False  True False  True False]


In [53]:
# any() and all()
arr = np.array([2, 4, 6, 8])
print("All even? :", np.all(arr % 2 == 0))   # True
print("Any > 10? :", np.any(arr > 10))        # False

All even? : True
Any > 10? : False


---

## 9️⃣ Handling NaN and Infinite Values

NaN (Not a Number) and Inf (Infinity) are special floating-point values that appear constantly in real data.

### Why do they appear?
- NaN: missing sensor reading, failed computation (0/0), data not recorded
- Inf: division by zero (1/0), overflow

In [54]:
# Creating NaN and Inf
nan_val = np.nan
inf_val = np.inf

print("NaN :", nan_val)
print("Inf :", inf_val)
print("-Inf:", -np.inf)
print()

# NaN arithmetic (NaN is contagious!)
print("NaN + 5  :", nan_val + 5)
print("NaN * 0  :", nan_val * 0)
print("NaN == NaN:", nan_val == nan_val)   # ⚠️ False! NaN is not equal to itself

NaN : nan
Inf : inf
-Inf: -inf

NaN + 5  : nan
NaN * 0  : nan
NaN == NaN: False


In [55]:
# Array with NaN values
data = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0, np.inf, -np.inf])
print("Data:", data)

Data: [  1.   2.  nan   4.  nan   6.  inf -inf]


In [56]:
# Detection
print("isnan    :", np.isnan(data))      # True where NaN
print("isinf    :", np.isinf(data))      # True where +Inf or -Inf
print("isfinite :", np.isfinite(data))   # True where normal number (not NaN, not Inf)
print("isposinf :", np.isposinf(data))   # True where +Inf only
print("isneginf :", np.isneginf(data))   # True where -Inf only

isnan    : [False False  True False  True False False False]
isinf    : [False False False False False False  True  True]
isfinite : [ True  True False  True False  True False False]
isposinf : [False False False False False False  True False]
isneginf : [False False False False False False False  True]


In [57]:
# Count NaNs
nan_count = np.sum(np.isnan(data))
print("Number of NaN values:", nan_count)

# Count Inf values
inf_count = np.sum(np.isinf(data))
print("Number of Inf values:", inf_count)

Number of NaN values: 2
Number of Inf values: 2


In [58]:
# Filter out NaN and Inf → keep only finite values
clean_data = data[np.isfinite(data)]
print("Original data:", data)
print("Clean data   :", clean_data)

Original data: [  1.   2.  nan   4.  nan   6.  inf -inf]
Clean data   : [1. 2. 4. 6.]


In [59]:
# Replace NaN with a fill value (imputation)
data2 = np.array([1.0, np.nan, 3.0, np.nan, 5.0])

# Replace NaN with 0
filled_zero = data2.copy()
filled_zero[np.isnan(filled_zero)] = 0
print("NaN → 0   :", filled_zero)

# Replace NaN with mean of valid values
filled_mean = data2.copy()
mean_val = np.nanmean(data2)   # nanmean ignores NaN
filled_mean[np.isnan(filled_mean)] = mean_val
print(f"NaN → mean({mean_val:.1f}):", filled_mean)

NaN → 0   : [1. 0. 3. 0. 5.]
NaN → mean(3.0): [1. 3. 3. 3. 5.]


In [142]:
data3 = np.array([1, 2, 4, 5])
print(np.sum(data3))

12


In [141]:
data3 = np.array([1.0, 2.0, 4.0, 5.0])
print(np.sum(data3))

12.0


In [60]:
# NaN-safe aggregation functions
data3 = np.array([1.0, 2.0, np.nan, 4.0, 5.0])

print("np.sum    (breaks with NaN):", np.sum(data3))
print("np.nansum (ignores NaN)    :", np.nansum(data3))
print()
print("np.mean    :", np.mean(data3))
print("np.nanmean :", np.nanmean(data3))
print()
print("np.nanmin  :", np.nanmin(data3))
print("np.nanmax  :", np.nanmax(data3))
print("np.nanstd  :", np.nanstd(data3))

np.sum    (breaks with NaN): nan
np.nansum (ignores NaN)    : 12.0

np.mean    : nan
np.nanmean : 3.0

np.nanmin  : 1.0
np.nanmax  : 5.0
np.nanstd  : 1.5811388300841898


In [61]:
# NaN only works with float arrays (not int!)
# This is why Pandas uses float for integer columns with missing values

try:
    int_arr_nan = np.array([1, 2, np.nan], dtype=np.int32)
except ValueError as e:
    print("Error:", e)

float_arr_nan = np.array([1, 2, np.nan], dtype=np.float64)   # works
print("Float array with NaN:", float_arr_nan)

Error: cannot convert float NaN to integer
Float array with NaN: [ 1.  2. nan]


---

## 🧪 Quick Recap

| Topic | Key Takeaway |
|---|---|
| Why NumPy | Faster, less memory, vectorized vs Python lists |
| ndarray | Homogeneous, N-dimensional, contiguous memory |
| Attributes | shape, ndim, dtype, size, itemsize, nbytes |
| Data types | Choose wisely — saves memory at scale |
| Indexing | 0-based, negative indexing, slices are views |
| Memory | itemsize × size = nbytes, C vs F contiguous |
| Type casting | Upcasting is automatic; use .astype() to downcast |
| Logical ops | Returns bool arrays; great for filtering/masking |
| NaN/Inf | Contagious; use isnan/isfinite; use nan-safe functions |

---

# 📝 Assignments

## Assignment 1 — Array Creation & Attributes

1. Create a 4×5 array filled with zeros using `dtype=np.float32`. Print its `shape`, `size`, `itemsize`, and `nbytes`.
2. Create a 1D array using `np.linspace` that goes from 0 to 100 with exactly 11 values.
3. Create a 3×3 identity matrix and print its diagonal values using `np.diag()`.
4. Create an array `[5, 10, 15, 20, 25, 30]` using `np.arange` (not `np.array`).
5. Given the array `arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])`, print its `shape`, `ndim`, and `size`.

In [85]:
# Assignment 1 — Your answers here
print("Q1. ")
# 1. Create a 4×5 array filled with zeros using `dtype=np.float32`. Print its `shape`, `size`, `itemsize`, and `nbytes`.
arr1 = np.zeros((4,5),dtype=np.float32)

print(arr1)

print("Shape of arr1:", arr1.shape)
print("size of arr1: ", arr1.size)
print("itemsize of arr1: ",arr1.itemsize)
print("nbytes of arr1: ",arr1.nbytes)

print("-"*20)
print("Q2. ")
# 2. Create a 1D array using `np.linspace` that goes from 0 to 100 with exactly 11 values.
print(np.linspace(0,100,11))

print("-"*20)
print("Q3. ")
# 3. Create a 3×3 identity matrix and print its diagonal values using `np.diag()`.
# np.diag() has two behaviors depending on what you pass it:

# Pass a 2D matrix → it extracts the diagonal elements
# Pass a 1D array → it creates a matrix with those values on the diagonal
arr_eye= np.eye(3)
diag = np.diag(arr_eye)
print(diag)

print("-"*20)
print("Q4. ")
# 4. Create an array `[5, 10, 15, 20, 25, 30]` using `np.arange` (not `np.array`).
print(np.arange(5,31,5))

print("-"*20)
print("Q5. ")
# 5. Given the array `arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])`, print its `shape`, `ndim`, and `size`.
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("Shape of arr: ",arr.shape)
print("ndim of arr: ",arr.ndim)
print("size of arr: ",arr.size)

Q1. 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Shape of arr1: (4, 5)
size of arr1:  20
itemsize of arr1:  4
nbytes of arr1:  80
--------------------
Q2. 
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
--------------------
Q3. 
[1. 1. 1.]
--------------------
Q4. 
[ 5 10 15 20 25 30]
--------------------
Q5. 
Shape of arr:  (2, 2, 2)
ndim of arr:  3
size of arr:  8


## Assignment 2 — Data Types & Memory

1. Create an array of 10 million elements filled with `1` using `int64`. Calculate its memory in MB. Then repeat with `int8`. What is the difference?
2. What dtype will NumPy choose if you mix `int32` and `float32`? Verify with code.
3. Create an array with values `[0, 1, 255]` and check if it can safely fit into `uint8`. Then cast it and verify.
4. Create an array of pi value `3.141592653589793` in `float16`, `float32`, and `float64`. Compare their precision.
5. What is the max value storable in `int8`? Use `np.iinfo(np.int8).max` to check.

In [96]:

# Assignment 2 — Your answers here
print("Q2. ")
# 1. Create an array of 10 million elements filled with `1` using `int64`. Calculate its memory in MB. Then repeat with `int8`. What is the difference?
arr1 = np.ones(10000000,dtype=np.int64)

print("Memory size of arr1 in MB: ", arr1.nbytes / 1024 / 1024 , " MB")

print("-"*20)
print("Q2. ")
# 2. What dtype will NumPy choose if you mix `int32` and `float32`? Verify with code.
iarr = np.array([1,2,3],dtype=np.int32)
farr = np.array([1.1,2.1,3.1],dtype=np.float32)
sarr = iarr + farr
print(sarr.dtype)
sarr = np.sum(iarr + farr)
print(sarr.dtype)

print("-"*20)
print("Q3. ")
# 3. Create an array with values `[0, 1, 255]` and check if it can safely fit into `uint8`. Then cast it and verify.
arr = np.array([0, 1, 255])
print("Type of arr: ", arr.dtype)
print(arr)
arr1 = arr.astype(np.uint8)
print("Type of arr1", arr1.dtype)
print(arr1)

print("-"*20)
print("Q4. ")
# 4. Create an array of pi value `3.141592653589793` in `float16`, `float32`, and `float64`. Compare their precision.
arr = np.array([3.141592653589793],dtype=np.float16)
print(arr[0])
arr = np.array([3.141592653589793],dtype=np.float32)
print(arr[0])
arr = np.array([3.141592653589793],dtype=np.float64)
print(arr[0])

print("-"*20)
print("Q5. ")
# 5. What is the max value storable in `int8`? Use `np.iinfo(np.int8).max` to check.
print(np.iinfo(np.int8).max)

Q2. 
Memory size of arr1 in MB:  76.2939453125  MB
--------------------
Q2. 
float64
float64
--------------------
Q3. 
Type of arr:  int32
[  0   1 255]
Type of arr1 uint8
[  0   1 255]
--------------------
Q4. 
3.14
3.1415927
3.141592653589793
--------------------
Q5. 
127


## Assignment 3 — Indexing & Slicing

Given:
```python
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
```

1. Extract the element `13`.
2. Extract the entire 3rd row.
3. Extract the entire 4th column.
4. Extract the sub-matrix: `[[7, 8], [12, 13]]`.
5. Reverse the array row-wise (last row becomes first). 
6. Extract every alternate element from the 2nd row.
7. Demonstrate that a slice is a view: modify slice and show original changes.
8. Use `.copy()` to safely modify without affecting the original.

In [116]:
# Assignment 3 — Your answers here
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print("-"*20)
print("Q1. ")
# 1. Extract the element `13`.
print(arr[2][2])

print("-"*20)
print("Q2. ")
# 2. Extract the entire 3rd row.
print(arr[2,:])

print("-"*20)
print("Q3. ")
# 3. Extract the entire 4th column.
print(arr[:,3])

print("-"*20)
print("Q4. ")
# 4. Extract the sub-matrix: `[[7, 8], [12, 13]]`.
print(arr[1:3,1:3])

print("-"*20)
print("Q5. ")
# 5. Reverse the array row-wise (last row becomes first). 
print(arr[::-1])

print("-"*20)
print("Q7. ")
# 7. Demonstrate that a slice is a view: modify slice and show original changes.
arr_copy = arr
print("original array: \n", arr)
print("copy array: \n", arr_copy)
print(arr_copy[0:2,0:2])
arr_copy[0:2,0:2]=[[10,20],[60,70]]
print("AFter changes","-"*20)
print("original array: \n", arr)
print("copy array: \n", arr_copy)


print("-"*20)
print("Q8. ")
# 8. Use `.copy()` to safely modify without affecting the original.
arr_copy = arr.copy()
print("original array: \n", arr)
print("copy array: \n", arr_copy)
print(arr_copy[0:2,0:2])
arr_copy[0:2,0:2]=[[10,20],[60,70]]
print("AFter changes","-"*20)
print("original array: \n", arr)
print("copy array: \n", arr_copy)

--------------------
Q1. 
13
--------------------
Q2. 
[11 12 13 14 15]
--------------------
Q3. 
[ 4  9 14 19]
--------------------
Q4. 
[[ 7  8]
 [12 13]]
--------------------
Q5. 
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
--------------------
Q7. 
original array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
copy array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2]
 [6 7]]
AFter changes --------------------
original array: 
 [[10 20  3  4  5]
 [60 70  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
copy array: 
 [[10 20  3  4  5]
 [60 70  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
--------------------
Q8. 
original array: 
 [[10 20  3  4  5]
 [60 70  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
copy array: 
 [[10 20  3  4  5]
 [60 70  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[10 20]
 [60 70]]
AFter changes --------------------
original array: 
 [[10 20  3  4  5]
 [60 70  8  9 10]


## Assignment 4 — Type Casting

1. Create `arr = np.array([1.8, 2.9, 3.1, 4.99, 5.0])`. Cast it to `int32`. What happens to decimals?
2. Create `arr = np.array([300, 150, 50], dtype=np.int32)`. Cast to `int8`. What is the result and why?
3. Mix a `float32` and `float64` array using addition. What is the output dtype?
4. Write a function `safe_downcast(arr, target_dtype)` that:
   - Checks if the values fit in the target dtype range
   - If yes: casts and returns the result
   - If no: prints a warning and returns the original array

In [126]:
# Assignment 4 — Your answers here
print("Q1. ")
# 1. Create `arr = np.array([1.8, 2.9, 3.1, 4.99, 5.0])`. Cast it to `int32`. What happens to decimals?
arr = np.array([1.8, 2.9, 3.1, 4.99, 5.0])
print(arr.astype(np.int32))


print("-"*20)
print("Q2. ")
# 2. Create `arr = np.array([300, 150, 50], dtype=np.int32)`. Cast to `int8`. What is the result and why?
arr = np.array([300, 150, 50], dtype=np.int32)
print(arr.astype(np.int8))

print("-"*20)
print("Q3. ")
# 3. Mix a `float32` and `float64` array using addition. What is the output dtype?
arr1 = np.array([1.2,1.3,1.4],dtype=np.float32)
arr2 = np.array([1.2,1.3,1.4],dtype=np.float64)
arr3 = arr1 + arr2
print(arr3)
print(arr3.dtype)

print("-"*20)
print("Q4. ")
# 4. Write a function `safe_downcast(arr, target_dtype)` that:
#    - Checks if the values fit in the target dtype range
#    - If yes: casts and returns the result
#    - If no: prints a warning and returns the original array

def safe_downcast(arr,target_dtype):
    min_val = np.iinfo(target_dtype).min
    max_val = np.iinfo(target_dtype).max
    arr_val = np.iinfo(arr.dtype).max
    print("min target dtype value: ", min_val)
    print("max target dtype value: ", max_val)
    print("current array dtype value: ", arr_val)
    if min_val <= arr_val <= max_val:
        return "successfully Converted array",arr.astype(target_dtype)
    else:
        return "Failed to convert array", arr

arr = np.array([1,3,4,5],dtype=np.int8)
target_dtype = np.int16
print("array beforeconversion type: ", arr.dtype)
message,arr=safe_downcast(arr,target_dtype)
print("message : ", message)
print("array value :\n",arr)
print("array after conversion type: ", arr.dtype)
print("-"*20)
arr = np.array([1,3000,4,5],dtype=np.int16)
target_dtype = np.int8
print("array beforeconversion type: ", arr.dtype)
message,arr=safe_downcast(arr,target_dtype)
print("message : ", message)
print("array value :\n",arr)
print("array after conversion type: ", arr.dtype)


Q1. 
[1 2 3 4 5]
--------------------
Q2. 
[  44 -106   50]
--------------------
Q3. 
[2.40000005 2.59999995 2.79999998]
float64
--------------------
Q4. 
array beforeconversion type:  int8
min target dtype value:  -32768
max target dtype value:  32767
current array dtype value:  127
message :  successfully Converted array
array value :
 [1 3 4 5]
array after conversion type:  int16
--------------------
array beforeconversion type:  int16
min target dtype value:  -128
max target dtype value:  127
current array dtype value:  32767
message :  Failed to convert array
array value :
 [   1 3000    4    5]
array after conversion type:  int16



## Assignment 5 — Logical Operations & Filtering

Given temperature readings over 30 days:
```python
temps = np.array([22, 35, 28, 41, 19, 37, 30, 25, 33, 18,
                  40, 29, 23, 36, 31, 27, 38, 20, 24, 34,
                  21, 39, 26, 32, 17, 43, 28, 35, 22, 30])
```

1. Find all days where temperature was **above 35°C** (heat wave).
2. Find all days where temperature was **below 20°C** (cold day).
3. Find days where temperature was **between 25°C and 35°C** (comfortable).
4. Count how many days were comfortable.
5. Find days that were either **heat waves** or **cold days** (extreme days).
6. Were **all** days above 15°C? Use `np.all()`.
7. Were **any** days above 42°C? Use `np.any()`.

In [ ]:
# Assignment 5 — Your answers here
temps = np.array([22, 35, 28, 41, 19, 37, 30, 25, 33, 18,
                  40, 29, 23, 36, 31, 27, 38, 20, 24, 34,
                  21, 39, 26, 32, 17, 43, 28, 35, 22, 30])


## Assignment 6 — NaN & Inf Handling (Data Cleaning)

Given sensor data from an IoT device:
```python
sensor = np.array([23.1, np.nan, 24.5, np.inf, 22.8, np.nan,
                   25.3, -np.inf, 21.9, 24.0, np.nan, 23.7])
```

1. Count the number of `NaN` values.
2. Count the number of `Inf` values (both +inf and -inf).
3. Extract only the valid (finite) readings.
4. Replace NaN values with the **mean** of all finite values.
5. Replace Inf values with the **max** finite value and -Inf with the **min** finite value.
6. Calculate `nanmean`, `nanmin`, `nanmax`, and `nanstd` of the sensor array.
7. **Bonus**: Write a single function `clean_sensor_data(arr)` that handles all of the above and returns a clean array.

In [ ]:
# Assignment 6 — Your answers here
sensor = np.array([23.1, np.nan, 24.5, np.inf, 22.8, np.nan,
                   25.3, -np.inf, 21.9, 24.0, np.nan, 23.7])


## 🏆 Capstone Challenge

You receive a dataset of monthly sales figures for 6 products across 12 months. Some values are missing (NaN) and some are erroneous (Inf or negative):

```python
sales = np.array([
    [1500, 1800, np.nan, 2100, 1950, 2300, np.nan, 1700, 2000, 2150, 1600, 1900],
    [800,  np.nan, 950, 1100, 850,  np.inf, 900,  1050, np.nan, 800,  920,  1000],
    [3000, 3200, 2900, np.nan, 3100, 3500, 3300, np.nan, 3050, 3400, 3150, 3600],
    [450,  500,  np.nan, 600,  -100, 550,  np.nan, 480,  520,  -np.inf, 490, 530],
    [2200, 2100, 2400, 2300, np.nan, 2500, 2350, 2450, 2100, 2300, np.nan, 2600],
    [100,  120,  90,   np.nan, 130, 110,  140,   np.nan, 100, 120,  np.inf, 115]
])
```

**Tasks:**
1. Print the shape of the dataset.
2. Count total NaN, Inf, and negative values.
3. Clean the data: replace NaN with row-wise nanmean, replace Inf/-Inf/negatives with 0.
4. After cleaning, find the product (row) with the highest total annual sales.
5. Find which month (column index) had the highest total sales across all products.
6. Find which months had total sales above the overall mean.
7. Cast the cleaned array to `float32` to save memory. How much memory was saved?

In [ ]:
# Capstone — Your answers here
sales = np.array([
    [1500, 1800, np.nan, 2100, 1950, 2300, np.nan, 1700, 2000, 2150, 1600, 1900],
    [800,  np.nan, 950, 1100, 850,  np.inf, 900,  1050, np.nan, 800,  920,  1000],
    [3000, 3200, 2900, np.nan, 3100, 3500, 3300, np.nan, 3050, 3400, 3150, 3600],
    [450,  500,  np.nan, 600,  -100, 550,  np.nan, 480,  520,  -np.inf, 490, 530],
    [2200, 2100, 2400, 2300, np.nan, 2500, 2350, 2450, 2100, 2300, np.nan, 2600],
    [100,  120,  90,   np.nan, 130, 110,  140,   np.nan, 100, 120,  np.inf, 115]
])
